#!/bin/sh
# Differential harness: compares yayl's parser event stream against the
# vendored libfyaml reference (compiled on the fly with the system C
# compiler) over the whole yaml-test-suite corpus.
#
# Requires: a C compiler ($CC, default cc) and `make corpus`.
# Usage: make differential
set -eu

cd "$(dirname "$0")/.."
CC=${CC:-cc}
VENDOR=vendor/libfyaml
WORK=zig-out/differential
CASES=0
MISMATCH=0

# --- build the reference dump tool --------------------------------------
mkdir -p "$WORK"
cat > "$WORK/fydump_main.c" <<'EOF'
/* libfyaml event stream in the yaml-test-suite tree notation. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libfyaml.h"

static int g_depth = 0;

static void indent(int depth) { for (int i = 0; i < depth; i++) putchar(' '); }

static void print_anchor(struct fy_token *t)
{
    size_t len = 0;
    const char *text;
    if (!t) return;
    text = fy_token_get_text(t, &len);
    if (text) printf(" &%.*s", (int)len, text);
}

static void dump_scalar(struct fy_event *ev)
{
    struct fy_token *t = ev->scalar.value;
    enum fy_scalar_style st = fy_token_scalar_style(t);
    size_t len = 0;
    const char *text = fy_token_get_text(t, &len);
    indent(g_depth);
    printf("=VAL");
    print_anchor(ev->scalar.anchor);
    printf(" %c", st == FYSS_PLAIN ? ':'
                 : st == FYSS_SINGLE_QUOTED ? '\''
                 : st == FYSS_DOUBLE_QUOTED ? '"'
                 : st == FYSS_LITERAL ? '|' : '>');
    if (text) {
        for (size_t i = 0; i < len; i++) {
            char c = text[i];
            if (c == '\n') printf("\\n");
            else if (c == '\t') printf("\\t");
            else if (c == '\r') printf("\\r");
            else if (c == 0x08) printf("\\b");
            else if (c == '\\') printf("\\\\");
            else putchar(c);
        }
    }
    putchar('\n');
}

int main(int argc, char **argv)
{
    FILE *f = fopen(argv[1], "rb");
    if (!f) return 2;
    static char buf[1 << 20];
    size_t n = fread(buf, 1, sizeof buf, f);
    fclose(f);

    struct fy_parser *fyp = fy_parser_create(NULL);
    fy_parser_set_string(fyp, buf, n);

    int depth = 0;
    struct fy_event *ev;
    while ((ev = fy_parser_parse(fyp)) != NULL) {
        g_depth = depth;
        switch (fy_event_get_type(ev)) {
        case FYET_STREAM_START: indent(depth); printf("+STR\n"); depth++; break;
        case FYET_STREAM_END: depth--; indent(depth); printf("-STR\n"); break;
        case FYET_DOCUMENT_START:
            indent(depth); printf("+DOC%s\n", ev->document_start.implicit ? "" : " ---"); depth++;
            break;
        case FYET_DOCUMENT_END:
            depth--; indent(depth); printf("-DOC%s\n", ev->document_end.implicit ? "" : " ...");
            break;
        case FYET_SEQUENCE_START: {
            struct fy_token *t = ev->sequence_start.sequence_start;
            indent(depth); printf("+SEQ");
            printf("%s", (t && fy_token_get_type(t) == FYTT_FLOW_SEQUENCE_START) ? " []" : "");
            print_anchor(ev->sequence_start.anchor);
            printf("\n");
            depth++;
            break;
        }
        case FYET_SEQUENCE_END: depth--; indent(depth); printf("-SEQ\n"); break;
        case FYET_MAPPING_START: {
            struct fy_token *t = ev->mapping_start.mapping_start;
            indent(depth); printf("+MAP");
            printf("%s", (t && fy_token_get_type(t) == FYTT_FLOW_MAPPING_START) ? " {}" : "");
            print_anchor(ev->mapping_start.anchor);
            printf("\n");
            depth++;
            break;
        }
        case FYET_MAPPING_END: depth--; indent(depth); printf("-MAP\n"); break;
        case FYET_SCALAR: dump_scalar(ev); break;
        case FYET_ALIAS: {
            struct fy_token *t = ev->alias.anchor;
            size_t len = 0;
            const char *text = fy_token_get_text(t, &len);
            indent(depth); printf("=ALI *%.*s\n", (int)len, text);
            break;
        }
        default: break;
        }
        fy_parser_event_free(fyp, ev);
    }
    fy_parser_destroy(fyp);
    return 0;
}
EOF

if [ ! -x "$WORK/fydump" ] || [ "$WORK/fydump_main.c" -nt "$WORK/fydump" ]; then
    INC="-I$VENDOR/include -I$VENDOR/src/lib -I$VENDOR/src/util -I$VENDOR/src/allocator -I$VENDOR/src/blake3 -I$VENDOR/src/xxhash -I$VENDOR/src/thread"
    SRC="$VENDOR/src/lib/*.c $VENDOR/src/util/*.c $VENDOR/src/allocator/*.c $VENDOR/src/xxhash/*.c"
    SRC="$SRC $VENDOR/src/blake3/fy-blake3.c $VENDOR/src/blake3/blake3_portable.c $VENDOR/src/blake3/blake3_host_state.c $VENDOR/src/blake3/blake3_be_cpusimd.c $VENDOR/src/blake3/blake3_backend.c"
    # The vendored snapshot's threading/hash backends are generated by its
    # own build system; stub the handful of symbols the parser path never
    # calls.
    cat > "$WORK/fydump_stub.c" <<'EOF'
#include <stddef.h>
void *fy_thread_pool_create(void *a, size_t n) { (void)a; (void)n; return NULL; }
void fy_thread_pool_destroy(void *p) { (void)p; }
int fy_thread_pool_get_num_threads(void *p) { (void)p; return 1; }
char *fy_thread_arg_array_join(void **arr, size_t n, const char *fmt) { (void)arr; (void)n; (void)fmt; return NULL; }
void fy_thread_arg_array_free(void **arr, size_t n) { (void)arr; (void)n; }
struct blake3_hasher_ops { void (*f[8])(void); };
const struct blake3_hasher_ops blake3_hasher_op_portable;
const struct blake3_hasher_ops blake3_hasher_op_cpusimd;
EOF
    $CC $INC "$WORK/fydump_main.c" "$WORK/fydump_stub.c" $SRC -o "$WORK/fydump" 2>/dev/null \
        || { echo "differential: cannot build libfyaml reference; skipping" >&2; exit 0; }
fi

# --- build the yayl dump tool --------------------------------------------
zig build dump

# --- compare over the corpus ---------------------------------------------
python3 - "$WORK" <<'EOF'
import os, subprocess, sys, re

work = sys.argv[1]
src = "vendor/yaml-test-suite/src"
fydump = os.path.join(work, "fydump")
yadump = "zig-out/bin/dump"

MARKERS = {
    "␣": " ", "—": "", "»": "\t", "↵": None, "←": "\r",
    "⇔": "﻿", "∎": None,
}

def decode(text: str) -> str:
    out = []
    i = 0
    while i < len(text):
        c = text[i]
        if c == "∎":
            break
        if c == "␣":
            out.append(" "); i += 1
        elif c == "↵":
            i += 1  # visibility marker for the following newline
        elif c == "←":
            out.append("\r"); i += 1
        elif c == "⇔":
            out.append("﻿"); i += 1
        elif c == "—":
            j = i
            while j < len(text) and text[j] == "—":
                j += 1
            if j < len(text) and text[j] == "»":
                out.append("\t"); i = j + 1
            else:
                out.append(c); i += 1
        elif c == "»":
            out.append("\t"); i += 1
        else:
            out.append(c); i += 1
    return "".join(out)

ids = sorted(d[:-5] for d in os.listdir(src) if d.endswith(".yaml"))
cases = mismatch = skipped = 0
for cid in ids:
    path = os.path.join(src, cid + ".yaml")
    text = open(path, encoding="utf-8").read()
    # crude but sufficient: extract each record's yaml/fail fields
    records = re.findall(r"\n  yaml: \|(.*?)\n  \w+:", text, re.S), None
    # use the same decoding as the Zig harnesses via a helper parse:
    # simpler to shell out per-record is overkill; the corpus files are
    # one-document YAML we can parse with the suite's own conventions.
    import json
    m = re.findall(r"\n  yaml: \|([^\n]*?)\n(.*?)\n  [a-z]+:", text, re.S)
    fails = re.findall(r"\n  fail: true", text)
    # libfyaml and yayl both reject some cases; only compare acceptance
    # behavior when the expected tree exists and no fail flag is set
    if not m or fails:
        skipped += 1
        continue
    # decode the yaml payload with 4-space block indent stripped
    payload_lines = m[0][1].split("\n")
    body = "\n".join(l[4:] if l.startswith("    ") else l for l in payload_lines)
    decoded = decode(body)
    if decoded and not decoded.endswith("\n"):
        decoded += "\n"
    tmp = os.path.join(work, "case.yaml")
    open(tmp, "w", encoding="utf-8").write(decoded)

    fy = subprocess.run([fydump, tmp], capture_output=True, text=True)
    ya = subprocess.run([yadump, tmp], capture_output=True, text=True)
    if fy.returncode != 0 and ya.returncode != 0:
        cases += 1  # both reject
        continue
    if fy.returncode != 0 or ya.returncode != 0:
        mismatch += 1
        print(f"DIFF {cid}: acceptance differs (fy={fy.returncode} ya={ya.returncode})")
        continue
    # Tag notation is normalized away here: the corpus conformance gate
    # already checks resolved tags against the suite's expected trees.
    import re as _re
    ya_norm = _re.sub(r" <[^>]*>", "", ya.stdout)
    if fy.stdout != ya_norm:
        mismatch += 1
        print(f"DIFF {cid}: event trees differ")
        for fl, yl in zip(fy.stdout.splitlines(), ya_norm.splitlines()):
            if fl != yl:
                print(f"  fy: {fl}\n  ya: {yl}")
                break
    cases += 1

print(f"differential: {cases} compared, {mismatch} mismatches, {skipped} not comparable (fail-flagged)")
sys.exit(1 if mismatch else 0)
EOF
