#!/bin/sh
# Merge-key SEMANTIC differential: compares the VALUES yayl produces with
# `resolve_merge_keys` against the values libfyaml produces with
# FYPCF_RESOLVE_DOCUMENT, over tests/fixtures/merge/.
#
# The emission oracle's `merged` mode already proves libfyaml can PARSE
# what yayl emits after resolution. It cannot prove the resolved values
# agree: a merge that picked the wrong source, or dropped an entry, still
# emits perfectly valid YAML. This gate is the one that sees that.
#
# Requires: a C compiler ($CC, default cc) and `make libfyaml`.
# Usage: make merge-differential
set -eu

cd "$(dirname "$0")/.."
CC=${CC:-cc}
VENDOR=vendor/libfyaml
WORK=zig-out/merge-differential

mkdir -p "$WORK"

# --- the libfyaml reference dumper ---------------------------------------
# Emits the SAME canonical grammar as tests/emit.zig `dump-merged`; see
# `dumpCanonical` there for the grammar and for what both sides drop.
cat > "$WORK/fymerge_main.c" <<'EOF'
/* Resolved-document value dump via FYPCF_RESOLVE_DOCUMENT. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libfyaml.h"

#define MAX_DEPTH 256

static int dump_node(struct fy_node *fyn, int depth);

static int dump_mapping(struct fy_node *fyn, int depth)
{
    void *iter = NULL;
    struct fy_node_pair *fynp;
    int count = 0;
    /* Count first: the grammar is length-prefixed on both sides. */
    while ((fynp = fy_node_mapping_iterate(fyn, &iter)) != NULL) count++;
    printf("{%d\n", count);
    iter = NULL;
    while ((fynp = fy_node_mapping_iterate(fyn, &iter)) != NULL) {
        if (dump_node(fy_node_pair_key(fynp), depth + 1) != 0) return -1;
        if (dump_node(fy_node_pair_value(fynp), depth + 1) != 0) return -1;
    }
    printf("}\n");
    return 0;
}

static int dump_sequence(struct fy_node *fyn, int depth)
{
    void *iter = NULL;
    struct fy_node *item;
    int count = 0;
    while ((item = fy_node_sequence_iterate(fyn, &iter)) != NULL) count++;
    printf("[%d\n", count);
    iter = NULL;
    while ((item = fy_node_sequence_iterate(fyn, &iter)) != NULL) {
        if (dump_node(item, depth + 1) != 0) return -1;
    }
    printf("]\n");
    return 0;
}

static int dump_node(struct fy_node *fyn, int depth)
{
    if (depth >= MAX_DEPTH) return -1;
    /* A NULL node is YAML's empty scalar, matching yayl's empty value. */
    if (!fyn) { printf("S0:\n"); return 0; }
    switch (fy_node_get_type(fyn)) {
    case FYNT_SCALAR: {
        size_t len = 0;
        const char *text = fy_node_get_scalar(fyn, &len);
        printf("S%zu:%.*s\n", text ? len : (size_t)0, (int)(text ? len : 0), text ? text : "");
        return 0;
    }
    case FYNT_SEQUENCE: return dump_sequence(fyn, depth);
    case FYNT_MAPPING: return dump_mapping(fyn, depth);
    default: return -1;
    }
}

int main(int argc, char **argv)
{
    FILE *f;
    static char buf[1 << 20];
    size_t n;
    struct fy_parse_cfg cfg;
    struct fy_document *fyd;
    struct fy_node *root;

    if (argc < 2) return 2;
    f = fopen(argv[1], "rb");
    if (!f) return 2;
    n = fread(buf, 1, sizeof buf, f);
    fclose(f);

    memset(&cfg, 0, sizeof cfg);
    cfg.flags = FYPCF_RESOLVE_DOCUMENT;
    fyd = fy_document_build_from_string(&cfg, buf, n);
    /* Status 3: libfyaml rejected or could not resolve this input. */
    if (!fyd) return 3;

    root = fy_document_root(fyd);
    printf("D1\n");
    if (!root) {
        printf("N\n");
    } else if (dump_node(root, 0) != 0) {
        fy_document_destroy(fyd);
        return 4;
    }
    fy_document_destroy(fyd);
    return 0;
}
EOF

if [ ! -x "$WORK/fymerge" ] || [ "$WORK/fymerge_main.c" -nt "$WORK/fymerge" ]; then
    INC="-I$VENDOR/include -I$VENDOR/src/lib -I$VENDOR/src/util -I$VENDOR/src/allocator -I$VENDOR/src/blake3 -I$VENDOR/src/xxhash -I$VENDOR/src/thread"
    SRC="$VENDOR/src/lib/*.c $VENDOR/src/util/*.c $VENDOR/src/allocator/*.c $VENDOR/src/xxhash/*.c"
    SRC="$SRC $VENDOR/src/blake3/fy-blake3.c $VENDOR/src/blake3/blake3_portable.c $VENDOR/src/blake3/blake3_host_state.c $VENDOR/src/blake3/blake3_be_cpusimd.c $VENDOR/src/blake3/blake3_backend.c"
    # Same stubs as scripts/differential.sh: the vendored snapshot's
    # threading/hash backends are generated by its own build system.
    cat > "$WORK/fymerge_stub.c" <<'EOF'
#include <stddef.h>
void *fy_thread_pool_create(void *a, size_t n) { (void)a; (void)n; return NULL; }
void fy_thread_pool_destroy(void *p) { (void)p; }
int fy_thread_pool_get_num_threads(void *p) { (void)p; return 1; }
char *fy_thread_arg_array_join(void **arr, size_t n, const char *fmt) { (void)arr; (void)n; (void)fmt; return NULL; }
void fy_thread_arg_array_free(void **arr, size_t n) { (void)arr; (void)n; }
struct blake3_hasher_ops { void (*f[8])(void); };
const struct blake3_hasher_ops blake3_hasher_op_portable;
const struct blake3_hasher_ops blake3_hasher_op_cpusimd;
EOF
    $CC $INC -D_GNU_SOURCE "$WORK/fymerge_main.c" "$WORK/fymerge_stub.c" $SRC -o "$WORK/fymerge" -lm \
        || { echo "merge-differential: FAILED to build libfyaml reference" >&2; exit 1; }
fi

# --- build the yayl dumper ------------------------------------------------
zig build emit

# --- compare --------------------------------------------------------------
python3 - "$WORK" <<'EOF'
import os, subprocess, sys

work = sys.argv[1]
fixtures = "tests/fixtures/merge"
fymerge = os.path.join(work, "fymerge")
emit = "zig-out/bin/emit"

# PORT NOTE (docs/design/merge-keys.md): yayl follows the permissive
# YAML 1.1 rule the libfyaml EVENT path implements -- a merge value may
# be a mapping directly, or a sequence containing direct mappings.
# libfyaml's DOCUMENT path (fy_document_resolve, the FYPCF_RESOLVE_DOCUMENT
# this gate drives) is stricter: alias-only. It also rejects a mapping
# that repeats a key, which a document with two `<<` entries does.
# Those fixtures cannot be compared, by design on both sides. They are
# listed here so every skip is COUNTED and named, never silent -- and
# each is still required to parse and resolve under yayl, so a skip can
# never hide a yayl failure.
UNCOMPARABLE = {
    "inline-mapping.yaml":
        "merge value is an inline mapping; libfyaml's document path is alias-only",
    "inline-in-sequence.yaml":
        "merge sequence holds inline mappings; libfyaml's document path is alias-only",
    "duplicate-merge-keys.yaml":
        "two `<<` entries in one mapping; libfyaml's document path rejects a repeated key",
}

# --- canonical-dump parsing and normalization ----------------------------
# Both dumpers emit the grammar documented in tests/emit.zig
# `dumpCanonical`. Mapping ENTRY ORDER is normalized away here, in ONE
# place rather than in each dumper, because the two libraries order a
# resolved mapping differently and neither is wrong: YAML mappings are
# unordered, and the spec does not say where merged entries land.
# libfyaml puts them before the mapping's own keys, yayl appends them.
# Sorting by the key's own canonical dump keeps the comparison strict
# about VALUES -- a merge that picked the wrong source still changes the
# value bound to a key, which no amount of reordering can hide.
# Sequence order is NOT normalized: there, order is the value.
def parse(lines, i):
    line = lines[i]
    tag = line[0]
    if tag == "S":
        return ("S", line), i + 1
    if tag == "N":
        return ("N", line), i + 1
    if tag == "[":
        n = int(line[1:])
        i += 1
        items = []
        for _ in range(n):
            node, i = parse(lines, i)
            items.append(node)
        assert lines[i] == "]", lines[i]
        return ("[", items), i + 1
    if tag == "{":
        n = int(line[1:])
        i += 1
        pairs = []
        for _ in range(n):
            k, i = parse(lines, i)
            v, i = parse(lines, i)
            pairs.append((k, v))
        assert lines[i] == "}", lines[i]
        return ("{", pairs), i + 1
    raise ValueError(f"bad canonical dump line: {line!r}")

def render(node):
    tag, body = node
    if tag in ("S", "N"):
        return [body]
    if tag == "[":
        out = [f"[{len(body)}"]
        for item in body:
            out += render(item)
        return out + ["]"]
    out = [f"{{{len(body)}"]
    for k, v in sorted(body, key=lambda kv: "\n".join(render(kv[0]))):
        out += render(k)
        out += render(v)
    return out + ["}"]

def normalize(text: str) -> str:
    lines = [l for l in text.split("\n") if l]
    assert lines[0].startswith("D"), lines[0] if lines else "<empty>"
    ndocs = int(lines[0][1:])
    out = [lines[0]]
    i = 1
    for _ in range(ndocs):
        node, i = parse(lines, i)
        out += render(node)
    return "\n".join(out)

names = sorted(f for f in os.listdir(fixtures) if f.endswith(".yaml"))
compared = mismatch = skipped = 0

for name in names:
    path = os.path.join(fixtures, name)
    out = os.path.join(work, "ya.dump")
    ya = subprocess.run([emit, path, out, "dump-merged"], capture_output=True, text=True)

    if name in UNCOMPARABLE:
        # Still hold yayl to its own contract on the skipped fixtures.
        if ya.returncode != 0:
            mismatch += 1
            print(f"DIFF {name}: yayl failed a fixture it is required to resolve "
                  f"(exit {ya.returncode}): {ya.stderr.strip()}")
        else:
            skipped += 1
            print(f"skip {name}: {UNCOMPARABLE[name]}")
        continue

    fy = subprocess.run([fymerge, path], capture_output=True, text=True)
    if fy.returncode != 0 or ya.returncode != 0:
        mismatch += 1
        print(f"DIFF {name}: acceptance differs (fy={fy.returncode} ya={ya.returncode})")
        if ya.stderr.strip():
            print(f"  ya: {ya.stderr.strip()}")
        continue

    fy_norm = normalize(fy.stdout)
    ya_norm = normalize(open(out, encoding="utf-8").read())
    if fy_norm != ya_norm:
        mismatch += 1
        print(f"DIFF {name}: resolved values differ")
        fl, yl = fy_norm.split("\n"), ya_norm.split("\n")
        for i in range(max(len(fl), len(yl))):
            a = fl[i] if i < len(fl) else "<eof>"
            b = yl[i] if i < len(yl) else "<eof>"
            if a != b:
                print(f"  line {i+1}\n    fy: {a}\n    ya: {b}")
                break
    else:
        compared += 1

print(f"merge-differential: {compared} compared, {mismatch} mismatches, "
      f"{skipped} not comparable (libfyaml document path is alias-only)")

# A gate that compared nothing must not report success -- same floor rule
# as scripts/differential.sh. Raise this when fixtures are added.
MIN_COMPARED = 7
if compared < MIN_COMPARED:
    print(f"merge-differential: FAILED -- only {compared} fixtures compared, "
          f"expected at least {MIN_COMPARED}")
    sys.exit(1)

sys.exit(1 if mismatch else 0)
EOF
